### ISSUE TITLE
Forced to have $hashed

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [howya/laravel_model_encryption#14]
in `setHashed()` in the `in_array` if the `$hashed` is not been set, there will be a error.. why just not use `in_array($key, $this->hashed ?? [])` ?

**Comment by dscdac** [comment]
Hey,

Good idea. Will add it in the next version:
https://github.com/howya/laravel_model_encryption/pull/16

Thanks!

**Comment by AlbertoSinigaglia** [comment]
@dscdac you're welcome! Thanks for the great package
