### ISSUE TITLE
The payload is invalid

### ISSUE THREAD

**Issue by allw1994** [howya/laravel_model_encryption#8]
Using laravel 5.7 the package seems to encrypt the data no problem, but cannot decrypt, instead throwing an invalid payload exception.

In tinker I even tried creating a new instance of the object, saving it then pulling it again and it I still cannot get it to decrypt.

Any ideas??

**Comment by allw1994** [comment]
Never mind attributes messing me around :-(

**Comment by howya** [comment]
Hi Adam,

Sorry, just seen this after the Christmas break. Glad you got the issue sorted.

Regards,

Rob
