### ISSUE TITLE
orWhereBi() - can we have this ?

### ISSUE THREAD

**Issue by nenads** [howya/laravel_model_encryption#9]

**Comment by howya** [comment]
Feel free to make a PR with tests, I'm not actively maintaining this due to work commitments.

**Comment by nenads** [comment]
if i do that today can we speed merge, so i can still use your repo ?

**Comment by howya** [comment]
Can't guarantee when I can get to it - why not folk it instead?

**Comment by nenads** [comment]
i will and will do PR, i hate to have it on my repo.. too much stuff to change in composer etc

**Comment by howya** [comment]
OK, closing issue
